name = "brainmelt/main"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"
generate_interfaces = ".scripts/generate_interfaces.luau"
generate_signals = ".scripts/generate_signals.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.56.2", target = "lune" }
selene = { name = "pesde/selene", version = "^0.29.0", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
charm-sync = { wally = "littensy/charm-sync", version = "^0.3.0" }
charm = { wally = "littensy/charm", version = "^0.10.0" }
lyra = { wally = "paradoxum-games/lyra", version = "^0.6.0" }
spring = { wally = "nightcycle/spring",version = "^1.0.0" }