return {
    Class = {
        ['Service'] = 'Service' :: 'Service',
        ['Singleton'] = 'Singleton' :: 'Singleton' ,
        ['Prototype'] = 'Prototype' :: 'Prototype',
    },
    EventType = {
        ['Bindable'] = 'Bindable' :: 'Bindable' ,
        ['Remote'] = 'Remote' :: 'Remote',
    },
    NodeStatus = {
        ['Idle'] = 'Idle',
        ['Running'] = 'Running',
        ['Completed'] = 'Completed',
        ['Cancelled'] = 'Cancelled',
    }
}